#!/bin/bash

#PBS -q normal
#PBS -N funcodec_test
#PBS -l select=1:ncpus=16:ngpus=4
#PBS -l walltime=119:59:00
#PBS -j oe

echo "worker start"
cd $PBS_O_WORKDIR
module load singularity
export SINGULARITY_BIND="/home/project:/home/project,/scratch:/scratch,/app:/app"
singularity run --nv /app/apps/containers/kaldi/kaldi-nvidia-22.04-py3.sif << EOF
source ~/miniconda3/bin/activate ~/miniconda3/envs/haoyang

echo "funcodec run"

sh nscc_train.sh

EOF
