#!/bin/bash

#PBS -q normal
#PBS -N GPUtest
#PBS -l select=1:ncpus=4:ngpus=2
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -o ~/FunCodec/egs/LibriTTS/codec/test/output.o

echo "pbs test"
cd $PBS_O_WORKDIR
module load singularity
export SINGULARITY_BIND="/home/project:/home/project,/scratch:/scratch,/app:/app"
singularity run --nv /app/apps/containers/kaldi/kaldi-nvidia-22.04-py3.sif << EOF
source ~/miniconda3/bin/activate ~/miniconda3/envs/haoyang
python ./GPUtest.py